# Generated by Django 4.2.2 on 2023-06-11 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_clients', '0002_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Симпатия', 'verbose_name_plural': 'Симпатии'},
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12, null=True, verbose_name='широта местоположения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12, null=True, verbose_name='долгота местоположения'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_from_user', to=settings.AUTH_USER_MODEL, verbose_name='симпатия от пользователя'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_to_user', to=settings.AUTH_USER_MODEL, verbose_name='симпатия пользователю'),
        ),
    ]
